name=input("Enter the name--")
reg_no=input("Enter the reg no--")
dept=input("Enter the dept--")
print(f"name--{name}")
print(f"-----------------")
print(f"reg no-{reg_no}")
print(f"-----------------")
print(f"dept--{dept}")
print(f"-----------------")